"""
institution_meta.py — display names and categories for all 124 CDR Open Banking institutions.

Duplicated in lambda/ and data-pipeline/ — keep in sync (same pattern as athena_helper.py).
Update both copies when adding or renaming banks in config.json.
"""

DISPLAY_NAMES: dict[str, str] = {
    "AFG_Home_Loans_Alpha":                         "AFG Home Loans",
    "AMP_-_My_AMP":                                 "AMP (My AMP)",
    "AMP_Bank_GO":                                  "AMP Bank Go",
    "ANZ":                                          "ANZ",
    "ANZ_Plus":                                     "ANZ Plus",
    "Alex.Bank":                                    "Alex Bank",
    "Arab_Bank_Australia_Limited":                  "Arab Bank Australia",
    "Aussie_Elevate":                               "Aussie Elevate",
    "Aussie_Home_Loans":                            "Aussie Home Loans",
    "Australian_Military_Bank":                     "Australian Military Bank",
    "Australian_Mutual_Bank_LTD":                   "Australian Mutual Bank",
    "Auswide_Bank_Ltd":                             "Auswide Bank",
    "BCU_Bank":                                     "BCU Bank",
    "BNK_Bank_(Goldfields_Money/BCHL)":             "BNK Bank (Goldfields Money)",
    "BOQ_Specialist":                               "BOQ Specialist",
    "BankSA":                                       "BankSA",
    "BankVic":                                      "BankVic",
    "Bank_Australia":                               "Bank Australia",
    "Bank_First":                                   "Bank First",
    "Bank_of_China":                                "Bank of China",
    "Bank_of_Melbourne":                            "Bank of Melbourne",
    "Bank_of_Queensland_Limited":                   "Bank of Queensland",
    "Bank_of_Sydney":                               "Bank of Sydney",
    "Bank_of_us":                                   "Bank of us",
    "Bankwest":                                     "Bankwest",
    "Bendigo_Bank":                                 "Bendigo Bank",
    "Beyond_Bank_Australia":                        "Beyond Bank Australia",
    "Border_Bank":                                  "Border Bank",
    "Broken_Hill_Bank":                             "Broken Hill Bank",
    "CBA":                                          "Commonwealth Bank",
    "CBA_-_CommBiz":                                "CommBiz (CBA Business)",
    "Cairns_bank":                                  "Cairns Bank",
    "Central_Murray_Bank":                          "Central Murray Credit Union",
    "Central_West_CUL":                             "Central West Credit Union",
    "Coastline_Bank":                               "Coastline Credit Union",
    "Coles_Credit_Cards":                           "Coles Credit Cards",
    "CommBank":                                     "CommBank",
    "CommFCU":                                      "Community First Credit Union",
    "Connective_Select":                            "Connective Select",
    "Credit_Union_SA":                              "Credit Union SA",
    "DDH_Graham":                                   "DDH Graham",
    "Darling_Downs_Bank":                           "Darling Downs Bank",
    "Defence_Bank":                                 "Defence Bank",
    "Dnister":                                      "Dnister Ukrainian Credit Co-op",
    "Easy_Street":                                  "Easy Street Financial Services",
    "Family_First":                                 "Family First Bank",
    "Fire_Service_Credit_Union":                    "Fire Service Credit Union",
    "Firefighters_Mutual_Bank":                     "Firefighters Mutual Bank",
    "First_Option_Bank":                            "First Option Bank",
    "G&C_Mutual_Bank":                              "G&C Mutual Bank",
    "Gateway_Bank":                                 "Gateway Bank",
    "Geelong_Bank":                                 "Geelong Bank",
    "Great_Southern_Bank":                          "Great Southern Bank",
    "Great_Southern_Bank_Business+":                "Great Southern Bank Business+",
    "Greater_Bank_Limited":                         "Greater Bank",
    "HSBC":                                         "HSBC Australia",
    "HSBC_Bank_Australia_Limited_–_Wholesale_Banking": "HSBC Wholesale Banking",
    "Health_Professionals_Bank":                    "Health Professionals Bank",
    "Heartland":                                    "Heartland Bank",
    "Horizon_Bank":                                 "Horizon Bank",
    "Hume_Bank":                                    "Hume Bank",
    "IMB_Bank":                                     "IMB Bank",
    "ING":                                          "ING Australia",
    "ING_BANK_(Australia)_Ltd":                     "ING Bank Australia",
    "Judo_Bank":                                    "Judo Bank",
    "Kogan_Money_Credit_Cards":                     "Kogan Money Credit Cards",
    "Laboratories_Credit_Union":                    "Laboratories Credit Union",
    "Liberty_Financial":                            "Liberty Financial",
    "ME_Bank":                                      "ME Bank",
    "ME_Bank_-_ME_Go":                              "ME Go",
    "MOVE_Bank":                                    "MOVE Bank",
    "Macquarie_Bank_Limited":                       "Macquarie Bank",
    "Maitland_Mutual_Limited":                      "Maitland Mutual",
    "MyCard":                                       "MyCard",
    "MyState_Bank":                                 "MyState Bank",
    "NAB":                                          "National Australia Bank",
    "NATIONAL_AUSTRALIA_BANK":                      "NAB Business",
    "NRMA_Home_Loans":                              "NRMA Home Loans",
    "Newcastle_Permanent_Building_Society":         "Newcastle Permanent",
    "Northern_Inland_Credit_Union_Limited":         "Northern Inland Credit Union",
    "ORANGE_CREDIT_UNION_LTD":                      "Orange Credit Union",
    "P&N_Bank":                                     "P&N Bank",
    "PayPal_Australia":                             "PayPal Australia",
    "People's_Choice_and_Heritage":                 "People's Choice & Heritage Bank",
    "Police_Bank":                                  "Police Bank",
    "Police_Credit_Union_Ltd":                      "Police Credit Union",
    "QBANK":                                        "QBANK",
    "Qantas_Money_Credit_Cards":                    "Qantas Money Credit Cards",
    "Qantas_Money_Home_Loans":                      "Qantas Money Home Loans",
    "Qudos_Bank":                                   "Qudos Bank",
    "Queensland_Country_Bank":                      "Queensland Country Bank",
    "RACQ_Bank":                                    "RACQ Bank",
    "RAMS_Financial_Group_Pty_Ltd":                 "RAMS",
    "RSL_Money":                                    "RSL Money",
    "Rabobank":                                     "Rabobank Australia",
    "Regional_Australia_Bank":                      "Regional Australia Bank",
    "Reliance_Bank":                                "Reliance Bank",
    "SWSbank":                                      "SWSbank",
    "Solo_by_MYOB":                                 "Solo by MYOB",
    "Southern_Cross_Credit_Union":                  "Southern Cross Credit Union",
    "St.George_Bank":                               "St.George Bank",
    "Summerland_Bank":                              "Summerland Bank",
    "Suncorp_Bank":                                 "Suncorp Bank",
    "TMCU":                                         "Transport Mutual Credit Union",
    "Teachers_Mutual_Bank":                         "Teachers Mutual Bank",
    "The_Capricornian":                             "The Capricornian",
    "The_Mac":                                      "The Mac Credit Union",
    "Thriday":                                      "Thriday",
    "Tiimely_Home":                                 "Tiimely Home",
    "Traditional_Credit_Union":                     "Traditional Credit Union",
    "Tyro_Banking":                                 "Tyro Banking",
    "Tyro_Payments":                                "Tyro Payments",
    "UBank":                                        "UBank",
    "UniBank":                                      "UniBank",
    "Unity_Bank":                                   "Unity Bank",
    "Unloan":                                       "Unloan",
    "Up":                                           "Up Bank",
    "Virgin_Money":                                 "Virgin Money Australia",
    "Westpac":                                      "Westpac",
    "Wise":                                         "Wise",
    "Woolworths_Team_Bank":                         "Woolworths Team Bank",
    "bankWAW":                                      "bankWAW",
    "gmcu":                                         "Goldfields Money",
    "in1bank_ltd.":                                 "in1bank",
}

CATEGORIES: dict[str, str] = {
    # ── Big 4 ──────────────────────────────────────────────────────────────────
    "ANZ":                                          "Big 4",
    "ANZ_Plus":                                     "Big 4",
    "CBA":                                          "Big 4",
    "CommBank":                                     "Big 4",
    "CBA_-_CommBiz":                                "Big 4",
    "NAB":                                          "Big 4",
    "NATIONAL_AUSTRALIA_BANK":                      "Big 4",
    "Westpac":                                      "Big 4",
    "BankSA":                                       "Big 4",
    "Bank_of_Melbourne":                            "Big 4",
    "St.George_Bank":                               "Big 4",
    "RAMS_Financial_Group_Pty_Ltd":                 "Big 4",
    "Bankwest":                                     "Big 4",
    "UBank":                                        "Big 4",

    # ── Regional / Challenger Banks ────────────────────────────────────────────
    "Auswide_Bank_Ltd":                             "Regional/Challenger",
    "Bank_Australia":                               "Regional/Challenger",
    "Bank_of_Queensland_Limited":                   "Regional/Challenger",
    "BOQ_Specialist":                               "Regional/Challenger",
    "Bendigo_Bank":                                 "Regional/Challenger",
    "Beyond_Bank_Australia":                        "Regional/Challenger",
    "BNK_Bank_(Goldfields_Money/BCHL)":             "Regional/Challenger",
    "Great_Southern_Bank":                          "Regional/Challenger",
    "Great_Southern_Bank_Business+":                "Regional/Challenger",
    "Greater_Bank_Limited":                         "Regional/Challenger",
    "Heartland":                                    "Regional/Challenger",
    "Hume_Bank":                                    "Regional/Challenger",
    "IMB_Bank":                                     "Regional/Challenger",
    "Judo_Bank":                                    "Regional/Challenger",
    "Macquarie_Bank_Limited":                       "Regional/Challenger",
    "ME_Bank":                                      "Regional/Challenger",
    "ME_Bank_-_ME_Go":                              "Regional/Challenger",
    "MyState_Bank":                                 "Regional/Challenger",
    "Newcastle_Permanent_Building_Society":         "Regional/Challenger",
    "P&N_Bank":                                     "Regional/Challenger",
    "QBANK":                                        "Regional/Challenger",
    "Queensland_Country_Bank":                      "Regional/Challenger",
    "RACQ_Bank":                                    "Regional/Challenger",
    "Regional_Australia_Bank":                      "Regional/Challenger",
    "Suncorp_Bank":                                 "Regional/Challenger",
    "BCU_Bank":                                     "Regional/Challenger",
    "Alex.Bank":                                    "Regional/Challenger",
    "ING":                                          "Regional/Challenger",
    "ING_BANK_(Australia)_Ltd":                     "Regional/Challenger",
    "Liberty_Financial":                            "Regional/Challenger",
    "Qudos_Bank":                                   "Regional/Challenger",
    "bankWAW":                                      "Regional/Challenger",
    "gmcu":                                         "Regional/Challenger",
    "in1bank_ltd.":                                 "Regional/Challenger",

    # ── Mortgage Specialists / Brokers ─────────────────────────────────────────
    "AFG_Home_Loans_Alpha":                         "Mortgage Specialist",
    "Aussie_Elevate":                               "Mortgage Specialist",
    "Aussie_Home_Loans":                            "Mortgage Specialist",
    "Connective_Select":                            "Mortgage Specialist",
    "DDH_Graham":                                   "Mortgage Specialist",
    "NRMA_Home_Loans":                              "Mortgage Specialist",
    "Qantas_Money_Home_Loans":                      "Mortgage Specialist",
    "Tiimely_Home":                                 "Mortgage Specialist",
    "Unloan":                                       "Mortgage Specialist",

    # ── Credit Unions & Mutuals ────────────────────────────────────────────────
    "Australian_Military_Bank":                     "Credit Union/Mutual",
    "Australian_Mutual_Bank_LTD":                   "Credit Union/Mutual",
    "BankVic":                                      "Credit Union/Mutual",
    "Bank_First":                                   "Credit Union/Mutual",
    "Border_Bank":                                  "Credit Union/Mutual",
    "Broken_Hill_Bank":                             "Credit Union/Mutual",
    "Cairns_bank":                                  "Credit Union/Mutual",
    "Central_Murray_Bank":                          "Credit Union/Mutual",
    "Central_West_CUL":                             "Credit Union/Mutual",
    "Coastline_Bank":                               "Credit Union/Mutual",
    "CommFCU":                                      "Credit Union/Mutual",
    "Credit_Union_SA":                              "Credit Union/Mutual",
    "Darling_Downs_Bank":                           "Credit Union/Mutual",
    "Defence_Bank":                                 "Credit Union/Mutual",
    "Dnister":                                      "Credit Union/Mutual",
    "Easy_Street":                                  "Credit Union/Mutual",
    "Family_First":                                 "Credit Union/Mutual",
    "Fire_Service_Credit_Union":                    "Credit Union/Mutual",
    "Firefighters_Mutual_Bank":                     "Credit Union/Mutual",
    "First_Option_Bank":                            "Credit Union/Mutual",
    "G&C_Mutual_Bank":                              "Credit Union/Mutual",
    "Gateway_Bank":                                 "Credit Union/Mutual",
    "Geelong_Bank":                                 "Credit Union/Mutual",
    "Health_Professionals_Bank":                    "Credit Union/Mutual",
    "Horizon_Bank":                                 "Credit Union/Mutual",
    "Laboratories_Credit_Union":                    "Credit Union/Mutual",
    "Maitland_Mutual_Limited":                      "Credit Union/Mutual",
    "MOVE_Bank":                                    "Credit Union/Mutual",
    "Northern_Inland_Credit_Union_Limited":         "Credit Union/Mutual",
    "ORANGE_CREDIT_UNION_LTD":                      "Credit Union/Mutual",
    "People's_Choice_and_Heritage":                 "Credit Union/Mutual",
    "Police_Bank":                                  "Credit Union/Mutual",
    "Police_Credit_Union_Ltd":                      "Credit Union/Mutual",
    "RSL_Money":                                    "Credit Union/Mutual",
    "Reliance_Bank":                                "Credit Union/Mutual",
    "SWSbank":                                      "Credit Union/Mutual",
    "Southern_Cross_Credit_Union":                  "Credit Union/Mutual",
    "Summerland_Bank":                              "Credit Union/Mutual",
    "TMCU":                                         "Credit Union/Mutual",
    "Teachers_Mutual_Bank":                         "Credit Union/Mutual",
    "The_Capricornian":                             "Credit Union/Mutual",
    "The_Mac":                                      "Credit Union/Mutual",
    "Traditional_Credit_Union":                     "Credit Union/Mutual",
    "UniBank":                                      "Credit Union/Mutual",
    "Unity_Bank":                                   "Credit Union/Mutual",
    "Woolworths_Team_Bank":                         "Credit Union/Mutual",

    # ── Neobanks / Fintechs ────────────────────────────────────────────────────
    "Thriday":                                      "Neobank/Fintech",
    "Tyro_Banking":                                 "Neobank/Fintech",
    "Tyro_Payments":                                "Neobank/Fintech",
    "Up":                                           "Neobank/Fintech",
    "Wise":                                         "Neobank/Fintech",
    "Solo_by_MYOB":                                 "Neobank/Fintech",
    "PayPal_Australia":                             "Neobank/Fintech",
    "MyCard":                                       "Neobank/Fintech",

    # ── Foreign Banks ──────────────────────────────────────────────────────────
    "Arab_Bank_Australia_Limited":                  "Foreign Bank",
    "Bank_of_China":                                "Foreign Bank",
    "Bank_of_Sydney":                               "Foreign Bank",
    "Bank_of_us":                                   "Foreign Bank",
    "HSBC":                                         "Foreign Bank",
    "HSBC_Bank_Australia_Limited_–_Wholesale_Banking": "Foreign Bank",
    "Rabobank":                                     "Foreign Bank",

    # ── Credit Cards ───────────────────────────────────────────────────────────
    "Coles_Credit_Cards":                           "Credit Card",
    "Kogan_Money_Credit_Cards":                     "Credit Card",
    "Qantas_Money_Credit_Cards":                    "Credit Card",
    "Virgin_Money":                                 "Credit Card",

    # ── Other ──────────────────────────────────────────────────────────────────
    "AMP_-_My_AMP":                                 "Regional/Challenger",
    "AMP_Bank_GO":                                  "Regional/Challenger",
}
